- id: '1566418107270'
  alias: Bagno Camera da Letto Movimento  ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015d4d01
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    service: switch.turn_on
- id: '1566418445609'
  alias: Bagno Camera da Letto Movimento OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015d4d01
    for: '5'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    service: switch.turn_off
- id: '1566418588293'
  alias: Porta Ingresso ON1
  trigger:
  - entity_id: binary_sensor.everspring_sm103_door_window_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_3
    service: switch.turn_on
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_4
    service: switch.turn_on
- id: '1566418588297'
  alias: Porta Ingresso ON2
  trigger:
  - entity_id: binary_sensor.everspring_sm103_door_window_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: timer.cancelletto
    state: active
  action:
  - service: rest_command.apricancello
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_3
    service: switch.turn_on
  - data:
      entity_id: timer.cancelletto
    service: timer.finish
- id: '1566418804488'
  alias: Porta Ingresso OFF
  trigger:
  - entity_id: binary_sensor.everspring_sm103_door_window_sensor_sensor
    for: '50'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_3
    service: switch.turn_off
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_4
    service: switch.turn_off
- id: '1566471167038'
  alias: Cabina Armadio ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000123201f
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_8
    service: switch.turn_on
- id: '1566471257541'
  alias: Cabina Armadio OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000123201f
    for: '1'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_8
    service: switch.turn_off
- id: '1566490518464'
  alias: Garage Porta ON
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d00022f137b
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.garage
    service: light.turn_on
- id: '1566490768871'
  alias: Garage Movimento ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015f049d
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.garage
    service: light.turn_on
- id: '1566490825127'
  alias: Garage Movimento OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015f049d
    for: '4'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.garage
    service: light.turn_off
- id: '1566490988501'
  alias: Scale Taverna da sensore scale ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000120cbde
    from: 'off'
    platform: state
    to: 'on'
  - entity_id: binary_sensor.motion_sensor_158d00024e7487
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.luce_scale_taverna
    service: light.turn_on
- id: '1566491211244'
  alias: Cucina ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00024e6ca3
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '150'
    condition: numeric_state
    entity_id: sensor.illumination_158d00024e6ca3
  action:
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_2
    service: switch.turn_on
- id: '1566491306172'
  alias: Cucina OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00024e6ca3
    for: '4'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_2
    service: switch.turn_off
- id: '1566507832101'
  alias: Scala Taverna OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d000120cbde
    from: 'on'
    platform: state
    to: 'off'
  - entity_id: binary_sensor.motion_sensor_158d000120cba5
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.luce_scale_taverna
    service: light.turn_off
- id: '1566509482385'
  alias: Frigo Sempre ON
  trigger:
  - entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgwpe_f_wall_plug_gen5_switch
    service: switch.turn_on
- id: '1566509660975'
  alias: Bagno Camera da Letto Porta ON
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002ecf03a
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    service: switch.turn_on
- id: 8676479df9d247669ef12e673133c8a8
  alias: Luci Esterne ON tramonto
  trigger:
  - event: sunset
    platform: sun
  condition:
  action:
  - entity_id: group.Luci_Esterno_Notte
    service: homeassistant.turn_on
- id: 8676479ef9d247669ef12e673133c8a8
  alias: Luci Esterne OFF alba
  trigger:
  - event: sunrise
    platform: sun
  condition:
  action:
  - entity_id: group.Luci_Esterno_Notte
    service: homeassistant.turn_off
- id: '1567793310687'
  alias: Ingresso Dentro on
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - below: '25'
    condition: numeric_state
    entity_id: sensor.illumination_158d00024e730c
  action:
  - data:
      entity_id: light.cespuglio_ingresso
    service: light.turn_on
- id: '1567793605472'
  alias: Ingresso Dentro off
  trigger:
  - entity_id: binary_sensor.fibaro_system_fgms001_motion_sensor_sensor
    for: '2'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: light.cespuglio_ingresso
    service: light.turn_off
- id: '1568032161493'
  alias: Bagno Primo Piano ON su Apertura Porta
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000316d485
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.luce_lavabo
    service: light.turn_on
  - data:
      entity_id: light.luce_doccia
    service: light.turn_on
  - data:
      entity_id: light.luce_wc
    service: light.turn_on
- id: '1568316012125'
  alias: oscurante aperta
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002ecefcd
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.07200341bcddc2f88de3
    service: switch.turn_on
- id: '1568316212600'
  alias: oscurante chiusa
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d0002ecefcd
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.07200341bcddc2f88de3
    service: switch.turn_off
- id: '1569954216309'
  alias: wc
  trigger:
  - entity_id: binary_sensor.vibration_158d0002a22bc6
    platform: state
    to: vibrate
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch
    service: switch.toggle
- id: '1570387848257'
  alias: Movimento Pavimento Alessandro ON
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015f047c
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    service: switch.turn_on
- id: '1570387944857'
  alias: Movimento Pavimento Alessandro OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00015f047c
    for: '5'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_2
    service: switch.turn_off
- id: '1570388061632'
  alias: Tavolo Salone OFF
  trigger:
  - entity_id: binary_sensor.motion_sensor_158d00024edfce
    for: '30'
    from: 'on'
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      entity_id: switch.fibaro_system_fgs221_double_relay_switch_2x1_5kw_switch_3
    service: switch.toggle
- id: '1570562325754'
  alias: Scale Taverna da porta scale on
  trigger:
  - entity_id: binary_sensor.door_window_sensor_158d000126aaab
    from: 'off'
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      entity_id: light.luce_scale_taverna
    service: light.turn_on
- id: '1570801078800'
  alias: Luci Portico On su Movimento
  description: ''
  trigger:
  - entity_id: binary_sensor.telecameraingresso_motion_detected
    from: 'off'
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_3
    service: switch.turn_on
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_4
    service: switch.turn_on
- id: '1570801244558'
  alias: Luci Portico Off su Movimento
  description: ''
  trigger:
  - entity_id: binary_sensor.telecameraingresso_motion_detected
    for: '2'
    from: 'on'
    platform: state
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_3
    service: switch.turn_off
  - data:
      entity_id: switch.fibaro_system_fgs223_double_relay_switch_4
    service: switch.turn_off
- id: '7272827881723'
  alias: WebHook
  description: ''
  trigger:
  - event_data:
      action: call_service
    event_type: ifttt_webhook_received
    platform: event
  condition: []
  action:
  - data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'
    service_template: '{{ trigger.event.data.service }}'
- action:
  - data_template:
      caption: Foto {{ trigger.event.data.file }}
      file: '{{ trigger.event.data.file }}'
    service: telegram_bot.send_photo
  alias: Oggetto Non Identificato
  condition: []
  id: '1120092824611'
  trigger:
  - platform: event
    event_type: image_processing.file_saved
- id: '7272827881653'
  alias: Notification Test Weekly TTS
  initial_state: 'on'
  trigger:
    platform: time
    at: '12:15:00'
  condition:
    condition: time
    weekday:
    - wed
  action:
  - service: notify.alexa_media
    data:
      target:
      - media_player.echo_dot_camera_da_letto
      - media_player.echo_show_cucina
      - media_player.echo_plus_salone
      title: Titolo per echo Show
      data:
        type: announce
      message: Messaggio di prova