#- platform: generic
#  name:  TelecameraCasetta
#  still_image_url: !secret TelecameraCasettastill
#  stream_source: !secret TelecameraCasettastream
#  username: !secret TelecameraCasettausername
#  password: !secret TelecameraCasettadahuapass
#
#- platform: generic
#  name:  TelecameraIngresso
#  still_image_url: !secret TelecameraIngressostill
#  stream_source: !secret TelecameraIngressostream
#  username: !secret TelecameraIngressousername
#  password: !secret TelecameraIngressodahuapass
#
#- platform: generic
#  name:  TelecameraPortico
#  still_image_url: !secret TelecameraPorticostill
#  stream_source: !secret TelecameraPorticostream
#  username: !secret TelecameraPorticousername
#  password: !secret TelecameraPorticodahuapass
#
#- platform: generic
#  name:  TelecameraSalone
#  still_image_url: !secret TelecameraSalonestill
#  stream_source: !secret TelecameraSalonestream
#  username: !secret TelecameraSaloneusername
#  password: !secret TelecameraSalonedahuapass
#
#- platform: generic
#  name:  TelecameraCucina
#  still_image_url: !secret TelecameraCucinastill
#  stream_source: !secret TelecameraCucinastream
#  username: !secret TelecameraCucinausername
#  password: !secret TelecameraCucinadahuapass
#

- platform: generic
  name:  TelecameraCitofono
  still_image_url: !secret TelecameraCitofonostill
  stream_source: !secret TelecameraCitofonostream
  authentication: digest
  username: !secret TelecameraCitofonousername
  password: !secret TelecameraCitofonodahuapass

- platform: generic
  name:  TV2
  still_image_url: rtsp://192.168.2.2:554

#- platform: generic
#  name:  TelecameraMonitor
#  still_image_url: !secret TelecameraMonitorstill
#  stream_source: !secret TelecameraMonitorstream
#  username: !secret TelecameraMonitorusername
#  password: !secret TelecameraMonitordahuapass

- platform: local_file
  file_path: "/home/reinan/.homeassistant/www/images/portico/Sicurezza Portico_latest_person.jpg"
  name: Ultima Persona Portico

- platform: local_file
  file_path: "/home/reinan/.homeassistant/www/images/ingresso/Sicurezza Ingresso_latest_person.jpg"
  name: Ultima Persona Ingresso

- platform: local_file
  file_path: "/home/reinan/.homeassistant/www/images/casetta/Sicurezza Casetta_latest_person.jpg"
  name: Ultima Persona casetta

- platform: local_file
  file_path: "/home/reinan/.homeassistant/www/images/citofono/Sicurezza Citofono_latest_person.jpg"
  name: Ultima Vista Citofono
