default_config:

# Configure a default setup of Home Assistant (frontend, api, etc)

system_health:

discovery:

mobile_app: 

homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret Location
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: !secret timezone

  packages: !include_dir_named packages

  whitelist_external_dirs:
    - /home/reinan/.homeassistant/www/
    - /home/reinan/.homeassistant/www/images/
    - /home/reinan/.homeassistant/www/images/portico/
    - /home/reinan/.homeassistant/www/images/ingresso/
    - /home/reinan/.homeassistant/www/images/citofono/
    - /home/reinan/.homeassistant/www/images/casetta/
    - /mnt/data2/video/
    - /tmp
#zones
#https://www.home-assistant.io/components/zone/

zone:
  - name: !secret SchoolBeatrice
    latitude: !secret SchoolBeatricelatitude
    longitude: !secret SchoolBeatricelongitude
    radius: 100
    icon: mdi:chair-school

  - name: !secret SchoolAlessandro
    latitude: !secret SchoolAlessandrolatitude
    longitude: !secret SchoolAlessandrolongitude
    radius: 100
    icon: mdi:chair-school

  - name: !secret WifeWork
    latitude: !secret WifeWorklatitude
    longitude: !secret WifeWorklongitude
    radius: 250
    icon: mdi:work

  - name: !secret Homelocation
    latitude:  !secret Homelocationlatitude
    longitude:  !secret Homelocationlongitude
    radius: 100
    icon: mdi:account-multiple

  - name: !secret CasaIvanalocation
    latitude:  !secret CasaIvanalocationlatitude
    longitude:  !secret CasaIvanalocationlongitude
    radius: 100
    icon: mdi:account-multiple

  - name: !secret CasaMarialocation
    latitude:  !secret CasaMarialocationlatitude
    longitude:  !secret CasaMarialocationlongitude
    radius: 100
    icon: mdi:account-multiple

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123
http:
#  api_password: !secret hasspass
  base_url: https://thereinas.it
#  ssl_certificate: /etc/letsencrypt/live/thereinas.it/fullchain.pem
#  ssl_key: /etc/letsencrypt/live/thereinas.it/privkey.pem

#panels
# https://www.home-assistant.io/components/panel_custom/

api:

panel_iframe:
#  mdiindex:
#    title: MDI Icon Index
#    icon: mdi:vector-square
#    url: https://cdn.rawgit.com/james-fry/home-assistant-mdi/efd95d7a/home-assistant-mdi.html
  dockerstatus:
    title: Docker Status
    icon: mdi:docker
    url: http://192.168.2.2:9900/#/containers
  combivox:
    title: Combivox
    icon: mdi:alarm
    url: http://combivox.fritz.box
panel_custom:
  - name: zwavegraph2
    sidebar_title: Z-Wave Graph
    sidebar_icon: mdi:access-point-network
    url_path: zwave

#######################################################
# lovelace : real men use CLI
########################################################

lovelace:
  mode: yaml

##############################################
#  DataLogging
##############################################

recorder:
  purge_keep_days: 5
  db_url: !secret mysqldb

#logging
logger:
  default: error
#  logs:
#    xiaomi_gateway: debug
#    homeassistant.components.xiaomi_aqara: debug

influxdb:
  host: !secret influxserver 
  port: !secret influxport
  database: hass
#  username: !secret influxuser
#  password: !secret influxdbpassword

cloud:

  # Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:


# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: it

#HACS
# https://community.home-assistant.io/t/custom-component-hacs/121727

hacs:
  token: !secret hacstoken
  appdaemon: true
  python_script: true
  theme: true

frontend:
  themes: !include_dir_merge_named /home/reinan/.homeassistant/themes/

############################################################
# platforms
############################################################

# Harmony 
# https://www.home-assistant.io/components/harmony/

remote:
  - platform: harmony
    name: Harmony
    host: Harmonyhub.fritz.box

# Xiaomi Aqara
# https://www.home-assistant.io/components/xiaomi_aqara/

xiaomi_aqara:
  gateways:
    - mac: 78:11:DC:B2:2B:4E
      key: !secret AqaraKeyTaverna
      host: XGTaverna.fritz.box
    - mac: 34:CE:00:82:96:03
      key: !secret AqaraKeyPianoTerra
      host: XGPianoTerra.fritz.box
    - mac: 7C:49:EB:19:03:79
      key: !secret AqaraKeyPrimoPiano
      host: XGPrimoPiano.fritz.box

# Tuya
tuya:
  username: !secret tuyauser
  password: !secret tuyapassword 
  country_code: 39


ambient_station:
  api_key: YOUR_API_KEY
  app_key: YOUR_APPLICATION_KEY

#clima
evohome:
  username: !secret evohomeuser
  password: !secret evohomepassword

dyson:
  username: !secret dysonusr
  password: !secret dysonpwd
  language: IT
  devices:
    - device_id: A1A-EU-MCA0437A
      device_ip: dysonhotcoolpure.fritz.box

#ifttt:
#  key: !secret IFTTKEY

#vehicles
bmw_connected_drive:
  name:
    username: !secret BMWUSER
    password: !secret BMWPWD
    region: "rest_of_world"

#home appliances
vacuum:
  - platform: xiaomi_miio
    host: aspirapolvere.fritz.box
    token: !secret VacuumKey

#locks and doors
lock:
  - platform: nuki
    host: AndroidService.fritz.box
    token: !secret nukitoken

cover:
  platform: opengarage
  covers:
      garage:
        host:  opengarage.fritz.box
        device_key: !secret opengaragekey

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_key
    allowed_chat_ids: 
      - !secret telegram_bot_chat_id

yeelight:
  devices:
    yeelink-light-strip1-ledlettoale.fritz.box:
      name: Led Letto Alessandro

alexa_media:
  accounts:
    - email: !secret amazonemail
      password: !secret amazonpassword
      url: amazon.it

circadian_lighting:

openuv:
  api_key: !secret openuvkey
  binary_sensors:
    monitored_conditions:
      - uv_protection_window
  sensors:
    monitored_conditions:
      - current_ozone_level
      - current_uv_index
      - current_uv_level
      - max_uv_index
      - safe_exposure_time_type_1
      - safe_exposure_time_type_2
      - safe_exposure_time_type_3
      - safe_exposure_time_type_4
      - safe_exposure_time_type_5
      - safe_exposure_time_type_6

hass_opensprinkler:
  host: opensprinkler.fritz.box
  password: !secret opensprinklerpassword

  
# https://github.com/DavidMStraub/homeassistant-homeconnect/blob/master/custom_components/homeconnect/switch.py
# Bosch Siemens Home Connect

homeconnect:
  client_id: !secret homeconnectclientid
  client_secret: !secret homeconnectclientsecret


#stream
# https://www.home-assistant.io/components/stream/
stream:

ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

#mqtt
#https://www.home-assistant.io/components/mqtt/

mqtt:
  broker: !secret mqttserver
  port: !secret mqttport
  client_id: hass
  keepalive: 60
  discovery: true
  discovery_prefix: homeassistant

amcrest:
  - host:   TelecameraIngresso.fritz.box
    name:  TelecameraIngresso
    username: !secret TelecameraIngressousername
    password: !secret TelecameraIngressodahuapass
    binary_sensors:
     - motion_detected
     - online
      
  - host:   TelecameraCasetta.fritz.box
    name:  TelecameraCasetta
    username: !secret TelecameraCasettausername
    password: !secret TelecameraCasettadahuapass
    binary_sensors:
     - motion_detected
     - online

  - host:   TelecameraPortico.fritz.box
    name:  TelecameraPortico
    username: !secret TelecameraPorticousername
    password: !secret TelecameraPorticodahuapass
    binary_sensors:
     - motion_detected
     - online
    
  - host:   TelecameraCucina.fritz.box
    name:  TelecameraCucina
    username: !secret TelecameraCucinausername
    password: !secret TelecameraCucinadahuapass
    binary_sensors:
     - motion_detected
     - online

  - host:   TelecameraSalone.fritz.box
    name:  TelecameraSalone
    username: !secret TelecameraSaloneusername
    password: !secret TelecameraSalonedahuapass
    binary_sensors: 
     - motion_detected
     - online
##   sensors:
##     - motion_detector
##   switches: 
  #    - motion_detection
  #    - motion_recording

  
  - host:   TelecameraLetto.fritz.box
    name:  TelecameraLetto
    username: !secret TelecameraLettousername
    password: !secret TelecameraLettodahuapass
    binary_sensors: 
     - motion_detected
     - online
##   sensors:
##     - motion_detector
#  switches: 
#    - motion_detection
#    - motion_recording


fritzbox_tools:
  host: "192.168.2.1"  # required
  username: !secret FritzUser
  password: !secret FritzPassword
  profile_on: "Illimitato"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
  profile_off: "Bloccato"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
#  profile_60min: "limitato60minuti"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
#  profile_30min: "limitato30minuti"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
#  profile_15min: "limitato15minuti"  # Optional. Needed if you want to switch between device profiles ("Zugangsprofile")
  devices: # Optional. If you don't want to expose a profile switch for just some of your network devices
    - "TabletAle"
    - "TelefonoAle"
    - "FireTvAle"


anniversaries:
  sensors:
  - name: Compleanno Giovanna
    date: '1969-07-03'
  - name: Shakespeare's Wedding Anniversary
    date: '1582-11-27'      

image_processing:
  - platform: deepstack_face
    ip_address: localhost
    port: 5500
    api_key: !secret deepstackkey
    timeout: 5
    detect_only: False
    scan_interval: 3600
    source:
      - entity_id: camera.telecamerasalone
        name: Visi Salone

  - platform: deepstack_face
    ip_address: localhost
    port: 5500
    api_key: !secret deepstackkey
    timeout: 5
    detect_only: False
    scan_interval: 3600
    source:
      - entity_id: camera.telecameracucina
        name: Visi Cucina

  - platform: deepstack_face
    ip_address: localhost
    port: 5500
    timeout: 5
    detect_only: False
    scan_interval: 3600
    source:
      - entity_id: camera.ultima_persona_citofono
        name: Visi Citofono

  - platform: deepstack_object
    ip_address: localhost
    port: 5500
    scan_interval: 3600 # Optional, in seconds
    save_file_folder: /home/reinan/.homeassistant/www/images/casetta/
    save_timestamped_file: True
    source:
      - entity_id: camera.telecameracasetta
        name: Sicurezza Casetta

  - platform: deepstack_object
    ip_address: localhost
    port: 5500
    scan_interval: 3600 # Optional, in seconds
    save_file_folder: /home/reinan/.homeassistant/www/images/portico/
    save_timestamped_file: True
    source:
      - entity_id: camera.telecameraportico
        name: Sicurezza Portico

  - platform: deepstack_object
    ip_address: localhost
    port: 5500
    scan_interval: 3600 # Optional, in seconds
    save_file_folder: /home/reinan/.homeassistant/www/images/ingresso/
    save_timestamped_file: True
    source:
      - entity_id: camera.telecameraingresso
        name: Sicurezza Ingresso

  - platform: deepstack_object
    ip_address: localhost
    port: 5500
    scan_interval: 3600 # Optional, in seconds
    save_file_folder: /home/reinan/.homeassistant/www/images/citofono/
    save_timestamped_file: True
    source:
      - entity_id: camera.telecameracitofono
        name: Sicurezza Citofono

ifttt:
  key: !secret iftttwebhookkey

twilio:
  account_sid: !secret trilliosid
  auth_token: !secret trilliotoken

breaking_changes:

glances:
  - host: !secret glancesserver

#image_processing:
# - platform: dlib_face_identify
#   source:
#    - entity_id: camera.telecameracucina
#    - entity_id: camera.telecameracitofono
#    - entity_id: camera.telecameracasetta
#    - entity_id: camera.telecameraingresso
#    - entity_id: camera.telecameraportico
#    - entity_id: camera.telecameraletto
#    - entity_id: camera.telecameramonitor
#    - entity_id: camera.telecamerasalone
#   faces:
#     Giovanna: /home/reinan/.homeassistant/www/images/Giovanna.jpg
#     Nicola: /home/reinan/.homeassistant/www/images/Nicola.jpg
#     Beatrice: /home/reinan/.homeassistant/www/images/Beatrice.jpg
#     Alessandro: /home/reinan/.homeassistant/www/images/Alessandro.jpg    
#  - platform: facebox
#    ip_address: reinasserver.fritz.box
#    port: 8180
#    source:
#      - entity_id: camera.telecameracucina
#        name: Camera Cucina
        
device_tracker: !include device_trackers.yaml
group: !include groups.yaml
light: !include lights.yaml
switch: !include switches.yaml
script: !include scripts.yaml
automation: !include automations.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
#intent_script: !include intent.yaml
media_player: !include media_players.yaml
timer: !include timers.yaml
camera: !include cameras.yaml
notify: !include notify.yaml
rest_command: !include restcommands.yaml
input_datetime: !include input_datetime.yaml

