title: Casa Reina
resources:
  - url: /community_plugin/lovelace-card-modder/card-modder.js?v=1
    type: js
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/banner-card/banner-card.js
    type: module
  - url: /community_plugin/button-card/button-card.js
    type: module
  - url: /community_plugin/calendar-card/calendar-card.js
    type: module
  - url: /community_plugin/circle-sensor-card/circle-sensor-card.js
    type: module
  - url: /community_plugin/content-card-remote-control/content-card-remote-control.js
    type: js    
  - url: /community_plugin/decluttering-card/decluttering-card.js
    type: module
  - url: /community_plugin/dual-gauge-card/dual-gauge-card.js
    type: js
  - url: /community_plugin/entity-attributes-card/entity-attributes-card.js
    type: js
  - url: /community_plugin/ext-weblink/ext-weblink.js
    type: js
  - url: /community_plugin/flex-table-card/flex-table-card.js
    type: js
  - url: /community_plugin/gauge-card/gauge-card.js
    type: js
  - url: /community_plugin/group-card/group-card.js
    type: js
  - url: /community_plugin/light-entity-card/light-entity-card.js
    type: js
  - url: /community_plugin/light-entity-row/light-entity-row.js
    type: js
  - url: /community_plugin/list-card/list-card.js
    type: js
  - url: /community_plugin/love-lock-card/love-lock-card.js
    type: js
  - url: /community_plugin/lovelace-card-mod/card-mod.js
    type: js
  - url: /community_plugin/lovelace-fold-entity-row/fold-entity-row.js
    type: js
  - url: /community_plugin/lovelace-home-feed-card/lovelace-home-feed-card.js
    type: js
  - url: /community_plugin/lovelace-html-card/html-card.js
    type: js
  - url: /community_plugin/lovelace-markdown-mod/markdown-mod.js
    type: js
  - url: /community_plugin/lovelace-slider-entity-row/slider-entity-row.js
    type: js
  - url: /community_plugin/lovelace-swipe-navigation/swipe-navigation.js
    type: js
  - url: /community_plugin/lovelace-text-input-row/lovelace-text-input-row.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: js
  - url: /community_plugin/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module
  - url: /community_plugin/mini-graph-card/mini-graph-card-bundle.js
    type: module
  - url: /community_plugin/mini-media-player/mini-media-player-bundle.js
    type: module
  - url: /community_plugin/monster-card/monster-card.js
    type: js
  - url: /community_plugin/plan-coordinates/plan-coordinates.js
    type: js
  - url: /community_plugin/secondaryinfo-entity-row/secondaryinfo-entity-row.js
    type: js
  - url: /community_plugin/simple-thermostat/simple-thermostat.js
    type: module
  - url: /community_plugin/simple-weather-card/simple-weather-card-bundle.js
    type: module
  - url: /community_plugin/spotify-card/spotify-card.js
    type: module
  - url: /community_plugin/state-attribute-element/state-attribute-element.js
    type: js
  - url: /community_plugin/state-element/state-element.js
    type: js
  - url: /community_plugin/surveillance-card/surveillance-card.js
    type: module
  - url: /community_plugin/swipe-card/swipe-card.js
    type: module
  - url: /community_plugin/text-action-element/text-action-element-bundle.js
    type: module
  - url: /community_plugin/text-element/text-element.js
    type: js
  - url: /community_plugin/vertical-stack-in-card/vertical-stack-in-card.js
    type: js
  - url: /community_plugin/weather-card/weather-card.js
    type: module
  - url: /community_plugin/compact-custom-header/compact-custom-header.js
    type: module
views:
  - title: Lightz
    name: Lightz
    path: Lightz
    panel: true
    cards:
      - type: vertical-stack
        cards:
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: light.luci_soggiorno
              color_type: card
            - type: "custom:button-card"
              entity: light.cespuglio_ingresso
              color_type: card
            - type: "custom:button-card"
              entity: light.cespuglio_divano
              color_type: card
            - type: "custom:button-card"
              entity: light.luce_tavolo
              color_type: card
#            - type: "custom:button-card"
#              color_type: blank-card
#            - type: "custom:button-card"
#              color_type: blank-card
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: light.cucina_2
              color_type: card
            - type: "custom:button-card"
              entity: light.luce_cucina
              color_type: card
#            - type: "custom:button-card"
#              color_type: blank-card
#            - type: "custom:button-card"
#              color_type: blank-card
#            - type: "custom:button-card"
#              color_type: blank-card
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: light.luci_camera_da_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.led_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.faretti_letto_camera_da_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.faretti_idromassaggio_camera_da_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.faretti_esterno_cabina_camera_da_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.lampada_sale_camera_da_letto
              color_type: card
            - type: "custom:button-card"
              entity: light.faretti_interno_cabina_camera_da_letto
              color_type: card
        - type: horizontal-stack
          cards:
            - type: "custom:button-card"
              entity: light.led_bagno
              color_type: card
            - type: "custom:button-card"
              icon: mdi:fan
              entity: switch.fibaro_system_fgs223_double_relay_switch
  - title: energy
    name: Energy
    path: energy
    panel: true
    cards:
    - type: vertical-stack
      cards:
      - type: "custom:mini-graph-card"
        name: Energia - 12h
        unit: W
        icon: mdi:power
        hours_to_show: 12
        points_per_hour: 10 
        hour24: true
        lower_bound: -2500
        upper_bound: 5000
        animate: true
        line_color: 
          - '#ff0000' 
          - '#288014' 
          - '#ebc634' 
        entities:
          - entity: sensor.consumo_casa
          - entity: sensor.produzione_casa
          - entity: sensor.scambio_casa
      - type: "custom:mini-graph-card"
        name: Energia - ultime due ore
        unit: W
        icon: mdi:power
        hours_to_show: 2
        points_per_hour: 60 
        hour24: true
        lower_bound: -2500
        upper_bound: 5000
        animate: true
        line_color: 
          - '#ff0000' 
          - '#288014' 
          - '#ebc634' 
        entities:
          - entity: sensor.consumo_casa
          - entity: sensor.produzione_casa
          - entity: sensor.scambio_casa
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.consumo_casa
            name: Consumo Casa
            min: 0
            max: 6000
            severity:
              green: 0
              yellow: 0
              red: 0
          - type: gauge
            entity: sensor.produzione_casa
            name: Produzione Casa
            min: 0
            max: 3000
            severity:
              green: 0
              yellow: 1000000
              red: 1000000
          - type: gauge
            entity: sensor.scambio_casa
            name: Scambio Casa
            min: -4000
            max: 4000
            severity:
              green: 0
              yellow: 0
              red: 100000000
      - type: horizontal-stack
        cards:
          - type: gauge
            entity: sensor.consumo_family_entertainment
            name: Consumo Family Entertainement
            min: 0
            max: 1500
            severity:
              green: 0
              yellow: 0
              red: 0
          - type: gauge
            entity: sensor.consumo_infrastruttura
            name: Consumo Infrastruttura
            min: 0
            max: 1500
            severity:
              green: 0
              yellow: 1000000
              red: 1000000
          - type: gauge
            entity: sensor.consumo_altro_salone
            name: Consumo Altro Salone
            min: 0
            max: 1500
            severity:
              green: 0
              yellow: 0
              red: 100000000


  - title: Clima 
    name: Clima
    path: clima
    panel: true
    cards:
    - type: vertical-stack
      cards:
      - type: horizontal-stack
        cards:
        - type: "custom:mini-graph-card"
          name: Clima Soggiorno ultime 2 ore
          unit: o
          icon: mdi:home-thermometer
          hours_to_show: 2
          points_per_hour: 6 
          hour24: true
          lower_bound: 5
          upper_bound: 30
          entities:
            - entity: sensor.temperatura_att_gio_e_nic
        - type: "custom:mini-graph-card"
          name: Clima Soggiorno 12 ore
          unit: o
          icon: mdi:home-thermometer
          hours_to_show: 12
          points_per_hour: 6 
          hour24: true
          lower_bound: 5
          upper_bound: 30
          entities:
            - entity: sensor.temperatura_att_gio_e_nic
            
        - type: "custom:simple-thermostat"
          entity: climate.gio_e_nic

  #          - entity: sensor.temperatura_att_gio_e_nic
  #          - entity: sensor.temperatura_att_bagno_gio_e_nic
#      - type  : thermostat
#        entity: climate.casa
#      - type: thermostat
#        entity: climate.casa
#      - type: thermostat
#        entity: climate.soggiorno
#      - type: thermostat
#        entity: climate.gio_e_nic
#      - type: thermostat
#        entity: climate.bagno_gio_nic
#      - type: "custom:mini-graph-card"
#        name: Clima Primo Piano
#        unit: o
#        icon: mdi:home-thermometer
#        hours_to_show: 24
#        points_per_hour: 6 
#        hour24: true
#        lower_bound: 5
#        upper_bound: 30
#        entities:
#          - entity: sensor.temperatura_att_casa
#          - entity: sensor.temperatura_att_beatrice
#          - entity: sensor.temperatura_att_alessandro
#          - entity: sensor.temperatura_att_bagno_su
#      - type: "custom:mini-graph-card"
#        name: Clima Taverna
#        unit: o
#        icon: mdi:home-thermometer
#        hours_to_show: 24
#        points_per_hour: 6 
#        hour24: true
#        lower_bound: 5
#        upper_bound: 30
#        entities:
#          - entity: sensor.temperatura_att_casa
#          - entity: sensor.temperatura_att_bagno_taverna
#          - entity: sensor.temperatura_att_letto_taverna
#          - entity: sensor.temperatura_att_salone_taverna
#          - entity: sensor.temperatura_att_studio
#